// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

const (
	API_KEYScopes = "API_KEY.Scopes"
)

// Defines values for ViewDirectorToursParamsTimePeriod.
const (
	FUTURE ViewDirectorToursParamsTimePeriod = "FUTURE"
	PAST   ViewDirectorToursParamsTimePeriod = "PAST"
)

// Valid indicates whether the value is a known member of the ViewDirectorToursParamsTimePeriod enum.
func (e ViewDirectorToursParamsTimePeriod) Valid() bool {
	switch e {
	case FUTURE:
		return true
	case PAST:
		return true
	default:
		return false
	}
}

// Defines values for ViewPlayerActiveResultsParamsRankingSystem.
const (
	ViewPlayerActiveResultsParamsRankingSystemMAIN  ViewPlayerActiveResultsParamsRankingSystem = "MAIN"
	ViewPlayerActiveResultsParamsRankingSystemWOMEN ViewPlayerActiveResultsParamsRankingSystem = "WOMEN"
	ViewPlayerActiveResultsParamsRankingSystemYOUTH ViewPlayerActiveResultsParamsRankingSystem = "YOUTH"
)

// Valid indicates whether the value is a known member of the ViewPlayerActiveResultsParamsRankingSystem enum.
func (e ViewPlayerActiveResultsParamsRankingSystem) Valid() bool {
	switch e {
	case ViewPlayerActiveResultsParamsRankingSystemMAIN:
		return true
	case ViewPlayerActiveResultsParamsRankingSystemWOMEN:
		return true
	case ViewPlayerActiveResultsParamsRankingSystemYOUTH:
		return true
	default:
		return false
	}
}

// Defines values for ViewPlayerActiveResultsParamsType.
const (
	ViewPlayerActiveResultsParamsTypeACTIVE    ViewPlayerActiveResultsParamsType = "ACTIVE"
	ViewPlayerActiveResultsParamsTypeINACTIVE  ViewPlayerActiveResultsParamsType = "INACTIVE"
	ViewPlayerActiveResultsParamsTypeNONACTIVE ViewPlayerActiveResultsParamsType = "NONACTIVE"
)

// Valid indicates whether the value is a known member of the ViewPlayerActiveResultsParamsType enum.
func (e ViewPlayerActiveResultsParamsType) Valid() bool {
	switch e {
	case ViewPlayerActiveResultsParamsTypeACTIVE:
		return true
	case ViewPlayerActiveResultsParamsTypeINACTIVE:
		return true
	case ViewPlayerActiveResultsParamsTypeNONACTIVE:
		return true
	default:
		return false
	}
}

// Defines values for RankingProParamsRankingSystem.
const (
	RankingProParamsRankingSystemOPEN  RankingProParamsRankingSystem = "OPEN"
	RankingProParamsRankingSystemWOMEN RankingProParamsRankingSystem = "WOMEN"
)

// Valid indicates whether the value is a known member of the RankingProParamsRankingSystem enum.
func (e RankingProParamsRankingSystem) Valid() bool {
	switch e {
	case RankingProParamsRankingSystemOPEN:
		return true
	case RankingProParamsRankingSystemWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for RankingWomenOpenParamsTournamentType.
const (
	RankingWomenOpenParamsTournamentTypeOPEN  RankingWomenOpenParamsTournamentType = "OPEN"
	RankingWomenOpenParamsTournamentTypeWOMEN RankingWomenOpenParamsTournamentType = "WOMEN"
)

// Valid indicates whether the value is a known member of the RankingWomenOpenParamsTournamentType enum.
func (e RankingWomenOpenParamsTournamentType) Valid() bool {
	switch e {
	case RankingWomenOpenParamsTournamentTypeOPEN:
		return true
	case RankingWomenOpenParamsTournamentTypeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for SeriesRegionsParamsSeriesCode.
const (
	ACS    SeriesRegionsParamsSeriesCode = "ACS"
	NACS   SeriesRegionsParamsSeriesCode = "NACS"
	WNACSO SeriesRegionsParamsSeriesCode = "WNACSO"
	WNACSW SeriesRegionsParamsSeriesCode = "WNACSW"
)

// Valid indicates whether the value is a known member of the SeriesRegionsParamsSeriesCode enum.
func (e SeriesRegionsParamsSeriesCode) Valid() bool {
	switch e {
	case ACS:
		return true
	case NACS:
		return true
	case WNACSO:
		return true
	case WNACSW:
		return true
	default:
		return false
	}
}

// Defines values for StatsCountryPlayerCountParamsRankType.
const (
	StatsCountryPlayerCountParamsRankTypeOPEN  StatsCountryPlayerCountParamsRankType = "OPEN"
	StatsCountryPlayerCountParamsRankTypeWOMEN StatsCountryPlayerCountParamsRankType = "WOMEN"
)

// Valid indicates whether the value is a known member of the StatsCountryPlayerCountParamsRankType enum.
func (e StatsCountryPlayerCountParamsRankType) Valid() bool {
	switch e {
	case StatsCountryPlayerCountParamsRankTypeOPEN:
		return true
	case StatsCountryPlayerCountParamsRankTypeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for StatsEventPeriodParamsRankType.
const (
	StatsEventPeriodParamsRankTypeOPEN  StatsEventPeriodParamsRankType = "OPEN"
	StatsEventPeriodParamsRankTypeWOMEN StatsEventPeriodParamsRankType = "WOMEN"
)

// Valid indicates whether the value is a known member of the StatsEventPeriodParamsRankType enum.
func (e StatsEventPeriodParamsRankType) Valid() bool {
	switch e {
	case StatsEventPeriodParamsRankTypeOPEN:
		return true
	case StatsEventPeriodParamsRankTypeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for StatsEventsByYearParamsRankType.
const (
	StatsEventsByYearParamsRankTypeOPEN  StatsEventsByYearParamsRankType = "OPEN"
	StatsEventsByYearParamsRankTypeWOMEN StatsEventsByYearParamsRankType = "WOMEN"
)

// Valid indicates whether the value is a known member of the StatsEventsByYearParamsRankType enum.
func (e StatsEventsByYearParamsRankType) Valid() bool {
	switch e {
	case StatsEventsByYearParamsRankTypeOPEN:
		return true
	case StatsEventsByYearParamsRankTypeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for StatsLargestTournamentsParamsRankType.
const (
	StatsLargestTournamentsParamsRankTypeOPEN  StatsLargestTournamentsParamsRankType = "OPEN"
	StatsLargestTournamentsParamsRankTypeWOMEN StatsLargestTournamentsParamsRankType = "WOMEN"
)

// Valid indicates whether the value is a known member of the StatsLargestTournamentsParamsRankType enum.
func (e StatsLargestTournamentsParamsRankType) Valid() bool {
	switch e {
	case StatsLargestTournamentsParamsRankTypeOPEN:
		return true
	case StatsLargestTournamentsParamsRankTypeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for StatsLucrativeToursParamsRankType.
const (
	StatsLucrativeToursParamsRankTypeOPEN  StatsLucrativeToursParamsRankType = "OPEN"
	StatsLucrativeToursParamsRankTypeWOMEN StatsLucrativeToursParamsRankType = "WOMEN"
)

// Valid indicates whether the value is a known member of the StatsLucrativeToursParamsRankType enum.
func (e StatsLucrativeToursParamsRankType) Valid() bool {
	switch e {
	case StatsLucrativeToursParamsRankTypeOPEN:
		return true
	case StatsLucrativeToursParamsRankTypeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for StatsOverallParamsSystemCode.
const (
	StatsOverallParamsSystemCodeOPEN  StatsOverallParamsSystemCode = "OPEN"
	StatsOverallParamsSystemCodeWOMEN StatsOverallParamsSystemCode = "WOMEN"
)

// Valid indicates whether the value is a known member of the StatsOverallParamsSystemCode enum.
func (e StatsOverallParamsSystemCode) Valid() bool {
	switch e {
	case StatsOverallParamsSystemCodeOPEN:
		return true
	case StatsOverallParamsSystemCodeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for StatsPointsPeriodParamsRankType.
const (
	StatsPointsPeriodParamsRankTypeOPEN  StatsPointsPeriodParamsRankType = "OPEN"
	StatsPointsPeriodParamsRankTypeWOMEN StatsPointsPeriodParamsRankType = "WOMEN"
)

// Valid indicates whether the value is a known member of the StatsPointsPeriodParamsRankType enum.
func (e StatsPointsPeriodParamsRankType) Valid() bool {
	switch e {
	case StatsPointsPeriodParamsRankTypeOPEN:
		return true
	case StatsPointsPeriodParamsRankTypeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for StatsStatePlayerCountParamsRankType.
const (
	StatsStatePlayerCountParamsRankTypeOPEN  StatsStatePlayerCountParamsRankType = "OPEN"
	StatsStatePlayerCountParamsRankTypeWOMEN StatsStatePlayerCountParamsRankType = "WOMEN"
)

// Valid indicates whether the value is a known member of the StatsStatePlayerCountParamsRankType enum.
func (e StatsStatePlayerCountParamsRankType) Valid() bool {
	switch e {
	case StatsStatePlayerCountParamsRankTypeOPEN:
		return true
	case StatsStatePlayerCountParamsRankTypeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for StatsStateTourCountParamsRankType.
const (
	StatsStateTourCountParamsRankTypeOPEN  StatsStateTourCountParamsRankType = "OPEN"
	StatsStateTourCountParamsRankTypeWOMEN StatsStateTourCountParamsRankType = "WOMEN"
)

// Valid indicates whether the value is a known member of the StatsStateTourCountParamsRankType enum.
func (e StatsStateTourCountParamsRankType) Valid() bool {
	switch e {
	case StatsStateTourCountParamsRankTypeOPEN:
		return true
	case StatsStateTourCountParamsRankTypeWOMEN:
		return true
	default:
		return false
	}
}

// Defines values for ViewLeagueInfoParamsTimePeriod.
const (
	ViewLeagueInfoParamsTimePeriodACTIVE   ViewLeagueInfoParamsTimePeriod = "ACTIVE"
	ViewLeagueInfoParamsTimePeriodHISTORY  ViewLeagueInfoParamsTimePeriod = "HISTORY"
	ViewLeagueInfoParamsTimePeriodUPCOMING ViewLeagueInfoParamsTimePeriod = "UPCOMING"
)

// Valid indicates whether the value is a known member of the ViewLeagueInfoParamsTimePeriod enum.
func (e ViewLeagueInfoParamsTimePeriod) Valid() bool {
	switch e {
	case ViewLeagueInfoParamsTimePeriodACTIVE:
		return true
	case ViewLeagueInfoParamsTimePeriodHISTORY:
		return true
	case ViewLeagueInfoParamsTimePeriodUPCOMING:
		return true
	default:
		return false
	}
}

// Defines values for TourSearchParamsRankType.
const (
	MAIN  TourSearchParamsRankType = "MAIN"
	WOMEN TourSearchParamsRankType = "WOMEN"
)

// Valid indicates whether the value is a known member of the TourSearchParamsRankType enum.
func (e TourSearchParamsRankType) Valid() bool {
	switch e {
	case MAIN:
		return true
	case WOMEN:
		return true
	default:
		return false
	}
}

// Defines values for TourSearchParamsEventType.
const (
	Keague     TourSearchParamsEventType = "Keague"
	Tournament TourSearchParamsEventType = "Tournament"
)

// Valid indicates whether the value is a known member of the TourSearchParamsEventType enum.
func (e TourSearchParamsEventType) Valid() bool {
	switch e {
	case Keague:
		return true
	case Tournament:
		return true
	default:
		return false
	}
}

// Defines values for TourSearchParamsPreRegistration.
const (
	TourSearchParamsPreRegistrationN TourSearchParamsPreRegistration = "N"
	TourSearchParamsPreRegistrationY TourSearchParamsPreRegistration = "Y"
)

// Valid indicates whether the value is a known member of the TourSearchParamsPreRegistration enum.
func (e TourSearchParamsPreRegistration) Valid() bool {
	switch e {
	case TourSearchParamsPreRegistrationN:
		return true
	case TourSearchParamsPreRegistrationY:
		return true
	default:
		return false
	}
}

// Defines values for TourSearchParamsOnlyWithResults.
const (
	TourSearchParamsOnlyWithResultsN TourSearchParamsOnlyWithResults = "N"
	TourSearchParamsOnlyWithResultsY TourSearchParamsOnlyWithResults = "Y"
)

// Valid indicates whether the value is a known member of the TourSearchParamsOnlyWithResults enum.
func (e TourSearchParamsOnlyWithResults) Valid() bool {
	switch e {
	case TourSearchParamsOnlyWithResultsN:
		return true
	case TourSearchParamsOnlyWithResultsY:
		return true
	default:
		return false
	}
}

// Defines values for TourSearchParamsDistanceUnit.
const (
	KForKilometers TourSearchParamsDistanceUnit = "k for Kilometers"
	MForMiles      TourSearchParamsDistanceUnit = "m for Miles"
)

// Valid indicates whether the value is a known member of the TourSearchParamsDistanceUnit enum.
func (e TourSearchParamsDistanceUnit) Valid() bool {
	switch e {
	case KForKilometers:
		return true
	case MForMiles:
		return true
	default:
		return false
	}
}

// Defines values for TourSearchParamsPointFilter.
const (
	NDefault TourSearchParamsPointFilter = "N (default)"
	Y        TourSearchParamsPointFilter = "Y"
)

// Valid indicates whether the value is a known member of the TourSearchParamsPointFilter enum.
func (e TourSearchParamsPointFilter) Valid() bool {
	switch e {
	case NDefault:
		return true
	case Y:
		return true
	default:
		return false
	}
}

// SearchDirectorsParams defines parameters for SearchDirectors.
type SearchDirectorsParams struct {
	// Name Name of the Director (not case sensitive)
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Count Number of results to return (default = 50)
	Count *int `form:"count,omitempty" json:"count,omitempty"`
}

// ViewDirectorToursParamsTimePeriod defines parameters for ViewDirectorTours.
type ViewDirectorToursParamsTimePeriod string

// ViewPlayerMultiParams defines parameters for ViewPlayerMulti.
type ViewPlayerMultiParams struct {
	// Players ID of the players, comma delimited
	Players string `form:"players" json:"players"`
}

// SearchPlayersParams defines parameters for SearchPlayers.
type SearchPlayersParams struct {
	// Name Name of the player (not case sensitive)
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Country Country Name or 2-digit code
	Country *string `form:"country,omitempty" json:"country,omitempty"`

	// Stateprov 2 digit State or Providence Code
	Stateprov *string `form:"stateprov,omitempty" json:"stateprov,omitempty"`

	// Tournament Name of tournament that a player may have played in. Partial Strings are accepted
	Tournament *string `form:"tournament,omitempty" json:"tournament,omitempty"`

	// Tourpos The position the player finished in
	Tourpos *float32 `form:"tourpos,omitempty" json:"tourpos,omitempty"`
}

// ViewPlayerActiveResultsParamsRankingSystem defines parameters for ViewPlayerActiveResults.
type ViewPlayerActiveResultsParamsRankingSystem string

// ViewPlayerActiveResultsParamsType defines parameters for ViewPlayerActiveResults.
type ViewPlayerActiveResultsParamsType string

// RankingCountryParams defines parameters for RankingCountry.
type RankingCountryParams struct {
	// StartPos Starting Position within results (for pagination)
	StartPos *float32 `form:"start_pos,omitempty" json:"start_pos,omitempty"`

	// Count How many Results to return
	Count *float32 `form:"count,omitempty" json:"count,omitempty"`

	// Country Country Name or Code to show (e.g. US, CA, NZ)
	Country string `form:"country" json:"country"`
}

// RankingCustomIDParams defines parameters for RankingCustomID.
type RankingCustomIDParams struct {
	// StartPos Starting Position within results (for pagination)
	StartPos *float32 `form:"start_pos,omitempty" json:"start_pos,omitempty"`

	// Count How many Results to return
	Count *float32 `form:"count,omitempty" json:"count,omitempty"`
}

// RankingProParamsRankingSystem defines parameters for RankingPro.
type RankingProParamsRankingSystem string

// RankingVirtualParams defines parameters for RankingVirtual.
type RankingVirtualParams struct {
	// StartPos Starting Position within results (for pagination)
	StartPos *float32 `form:"start_pos,omitempty" json:"start_pos,omitempty"`

	// Count How many Results to return
	Count *float32 `form:"count,omitempty" json:"count,omitempty"`
}

// RankingWomenOpenParams defines parameters for RankingWomenOpen.
type RankingWomenOpenParams struct {
	// StartPos Starting Position within results (for pagination)
	StartPos *float32 `form:"start_pos,omitempty" json:"start_pos,omitempty"`

	// Count How many Results to return
	Count *float32 `form:"count,omitempty" json:"count,omitempty"`
}

// RankingWomenOpenParamsTournamentType defines parameters for RankingWomenOpen.
type RankingWomenOpenParamsTournamentType string

// RankingWpprParams defines parameters for RankingWppr.
type RankingWpprParams struct {
	// StartPos Starting Position within results (for pagination)
	StartPos *float32 `form:"start_pos,omitempty" json:"start_pos,omitempty"`

	// Count How many Results to return
	Count *float32 `form:"count,omitempty" json:"count,omitempty"`
}

// RankingYouthParams defines parameters for RankingYouth.
type RankingYouthParams struct {
	// StartPos Starting Position within results (for pagination)
	StartPos *float32 `form:"start_pos,omitempty" json:"start_pos,omitempty"`

	// Count How many Results to return
	Count *float32 `form:"count,omitempty" json:"count,omitempty"`
}

// SeriesRegionOverallStandingsParams defines parameters for SeriesRegionOverallStandings.
type SeriesRegionOverallStandingsParams struct {
	// Year Which year of the series to lookup (default is current year)
	Year *float32 `form:"year,omitempty" json:"year,omitempty"`
}

// SeriesPlayersCardParams defines parameters for SeriesPlayersCard.
type SeriesPlayersCardParams struct {
	// Year Which year of the series to lookup (default is current year)
	Year *float32 `form:"year,omitempty" json:"year,omitempty"`

	// RegionCode Which region to get the player's card from (e.g. OH)
	RegionCode string `form:"region_code" json:"region_code"`
}

// SeriesRegionsParams defines parameters for SeriesRegions.
type SeriesRegionsParams struct {
	// Year Speific Year for the Series (defaults to current year)
	Year *int `form:"year,omitempty" json:"year,omitempty"`
}

// SeriesRegionsParamsSeriesCode defines parameters for SeriesRegions.
type SeriesRegionsParamsSeriesCode string

// SeriesRegionRegionStandingsParams defines parameters for SeriesRegionRegionStandings.
type SeriesRegionRegionStandingsParams struct {
	// Year Which year of the series to lookup (default is current year)
	Year *float32 `form:"year,omitempty" json:"year,omitempty"`

	// RegionCode Code of the region for the standings to be returned
	RegionCode string `form:"region_code" json:"region_code"`
}

// SeriesRegionRegionStatsParams defines parameters for SeriesRegionRegionStats.
type SeriesRegionRegionStatsParams struct {
	// Year Which year of the series to lookup (default is current year)
	Year *float32 `form:"year,omitempty" json:"year,omitempty"`

	// RegionCode Code of the region for the standings to be returned
	RegionCode string `form:"region_code" json:"region_code"`
}

// SeriesRegionTourParams defines parameters for SeriesRegionTour.
type SeriesRegionTourParams struct {
	// Year Which year of the series to lookup (default is current year)
	Year *float32 `form:"year,omitempty" json:"year,omitempty"`

	// RegionCode Code of the region for the standings to be returned
	RegionCode string `form:"region_code" json:"region_code"`
}

// StatsCountryPlayerCountParams defines parameters for StatsCountryPlayerCount.
type StatsCountryPlayerCountParams struct {
	// RankType Pull stats for specific ranking types. Default is OPEN
	RankType *StatsCountryPlayerCountParamsRankType `form:"rank_type,omitempty" json:"rank_type,omitempty"`
}

// StatsCountryPlayerCountParamsRankType defines parameters for StatsCountryPlayerCount.
type StatsCountryPlayerCountParamsRankType string

// StatsEventPeriodParams defines parameters for StatsEventPeriod.
type StatsEventPeriodParams struct {
	// RankType Pull stats for specific ranking types. Default is OPEN
	RankType *StatsEventPeriodParamsRankType `form:"rank_type,omitempty" json:"rank_type,omitempty"`

	// CountryCode Filters to specific countries
	CountryCode *string `form:"country_code,omitempty" json:"country_code,omitempty"`

	// StartDate Start Date of period range
	StartDate *string `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate End Date of period range
	EndDate *string `form:"end_date,omitempty" json:"end_date,omitempty"`

	// Limit Total number to of records to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// StatsEventPeriodParamsRankType defines parameters for StatsEventPeriod.
type StatsEventPeriodParamsRankType string

// StatsEventsByYearParams defines parameters for StatsEventsByYear.
type StatsEventsByYearParams struct {
	// RankType Pull stats for specific ranking types. Default is OPEN
	RankType *StatsEventsByYearParamsRankType `form:"rank_type,omitempty" json:"rank_type,omitempty"`

	// CountryCode Filters down to a specific country
	CountryCode *string `form:"country_code,omitempty" json:"country_code,omitempty"`
}

// StatsEventsByYearParamsRankType defines parameters for StatsEventsByYear.
type StatsEventsByYearParamsRankType string

// StatsLargestTournamentsParams defines parameters for StatsLargestTournaments.
type StatsLargestTournamentsParams struct {
	// RankType Pull stats for specific ranking types. Default is OPEN
	RankType *StatsLargestTournamentsParamsRankType `form:"rank_type,omitempty" json:"rank_type,omitempty"`

	// CountryCode Filters to specific countries
	CountryCode *string `form:"country_code,omitempty" json:"country_code,omitempty"`
}

// StatsLargestTournamentsParamsRankType defines parameters for StatsLargestTournaments.
type StatsLargestTournamentsParamsRankType string

// StatsLucrativeToursParams defines parameters for StatsLucrativeTours.
type StatsLucrativeToursParams struct {
	// Major Set to 'N' to exclude Major Tournaments [default is 'Y']
	Major *string `form:"major,omitempty" json:"major,omitempty"`

	// RankType Pull stats for specific ranking types. Default is OPEN
	RankType *StatsLucrativeToursParamsRankType `form:"rank_type,omitempty" json:"rank_type,omitempty"`

	// CountryCode Filters to specific countries
	CountryCode *string `form:"country_code,omitempty" json:"country_code,omitempty"`
}

// StatsLucrativeToursParamsRankType defines parameters for StatsLucrativeTours.
type StatsLucrativeToursParamsRankType string

// StatsOverallParams defines parameters for StatsOverall.
type StatsOverallParams struct {
	// SystemCode Pull stats for specific ranking types. Default is OPEN
	SystemCode *StatsOverallParamsSystemCode `form:"system_code,omitempty" json:"system_code,omitempty"`
}

// StatsOverallParamsSystemCode defines parameters for StatsOverall.
type StatsOverallParamsSystemCode string

// StatsPointsPeriodParams defines parameters for StatsPointsPeriod.
type StatsPointsPeriodParams struct {
	// RankType Pull stats for specific ranking types. Default is OPEN
	RankType *StatsPointsPeriodParamsRankType `form:"rank_type,omitempty" json:"rank_type,omitempty"`

	// CountryCode Filters to specific countries
	CountryCode *string `form:"country_code,omitempty" json:"country_code,omitempty"`

	// StartDate Start Date of period range
	StartDate *string `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate End date of period range
	EndDate *string `form:"end_date,omitempty" json:"end_date,omitempty"`

	// Limit Total number to of records to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// StatsPointsPeriodParamsRankType defines parameters for StatsPointsPeriod.
type StatsPointsPeriodParamsRankType string

// StatsStatePlayerCountParams defines parameters for StatsStatePlayerCount.
type StatsStatePlayerCountParams struct {
	// RankType Pull stats for specific ranking types. Default is OPEN
	RankType *StatsStatePlayerCountParamsRankType `form:"rank_type,omitempty" json:"rank_type,omitempty"`
}

// StatsStatePlayerCountParamsRankType defines parameters for StatsStatePlayerCount.
type StatsStatePlayerCountParamsRankType string

// StatsStateTourCountParams defines parameters for StatsStateTourCount.
type StatsStateTourCountParams struct {
	// RankType Pull stats for specific ranking types. Default is OPEN
	RankType *StatsStateTourCountParamsRankType `form:"rank_type,omitempty" json:"rank_type,omitempty"`
}

// StatsStateTourCountParamsRankType defines parameters for StatsStateTourCount.
type StatsStateTourCountParamsRankType string

// ViewLeagueInfoParamsTimePeriod defines parameters for ViewLeagueInfo.
type ViewLeagueInfoParamsTimePeriod string

// TourSearchParams defines parameters for TourSearch.
type TourSearchParams struct {
	// Name Search based on text string against Tournament Names
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Country Search based on the Country of the Tournament
	Country *string `form:"country,omitempty" json:"country,omitempty"`

	// Stateprov Search based on the State/Provience/Region of the Tournament
	Stateprov *string `form:"stateprov,omitempty" json:"stateprov,omitempty"`

	// StartDate Narrow search to only include results beyond a date. If not provided, today's date is used
	StartDate *string `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate Narrow search to only include results up to a certain date
	EndDate *string `form:"end_date,omitempty" json:"end_date,omitempty"`

	// RankType Search only calendar entries for specific ranking systems
	RankType *TourSearchParamsRankType `form:"rank_type,omitempty" json:"rank_type,omitempty"`

	// EventType Search only calendar entries for specific event type
	EventType *TourSearchParamsEventType `form:"event_type,omitempty" json:"event_type,omitempty"`

	// StartPos Start a specific position in the list that is returned. Default is position
	StartPos *int `form:"start_pos,omitempty" json:"start_pos,omitempty"`

	// Total Total number of calendar entries to return
	Total *int `form:"total,omitempty" json:"total,omitempty"`

	// DirectorName Narrow search to only include tournaments for a particular director
	DirectorName *string `form:"director_name,omitempty" json:"director_name,omitempty"`

	// PreRegistration Narrow search to only include tournaments that requires preregistration
	PreRegistration *TourSearchParamsPreRegistration `form:"pre_registration,omitempty" json:"pre_registration,omitempty"`

	// OnlyWithResults Narrow search to only include tournaments that have submitted results
	OnlyWithResults *TourSearchParamsOnlyWithResults `form:"only_with_results,omitempty" json:"only_with_results,omitempty"`

	// Latitude Narrow search to a region, based on latitude and longitude with radius and distance unit
	Latitude *string `form:"latitude,omitempty" json:"latitude,omitempty"`

	// Longitude Narrow search to a region, based on latitude and longitude with radius and distance unit
	Longitude *string `form:"longitude,omitempty" json:"longitude,omitempty"`

	// Radius Narrow search to a region, based on latitude and longitude with radius and distance unit
	Radius *float32 `form:"radius,omitempty" json:"radius,omitempty"`

	// DistanceUnit Narrow search to a region, based on latitude and longitude with radius and distance unit
	DistanceUnit *TourSearchParamsDistanceUnit `form:"distance_unit,omitempty" json:"distance_unit,omitempty"`

	// MinPoints Minimum Number of Points a Tournament must be worth
	MinPoints *float32 `form:"min_points,omitempty" json:"min_points,omitempty"`

	// MaxPoints Maximum Number of Points a Tournament can be worth
	MaxPoints *float32 `form:"max_points,omitempty" json:"max_points,omitempty"`

	// PointFilter Flag to indicate the search should use the points range values
	PointFilter *TourSearchParamsPointFilter `form:"point_filter,omitempty" json:"point_filter,omitempty"`
}

// TourSearchParamsRankType defines parameters for TourSearch.
type TourSearchParamsRankType string

// TourSearchParamsEventType defines parameters for TourSearch.
type TourSearchParamsEventType string

// TourSearchParamsPreRegistration defines parameters for TourSearch.
type TourSearchParamsPreRegistration string

// TourSearchParamsOnlyWithResults defines parameters for TourSearch.
type TourSearchParamsOnlyWithResults string

// TourSearchParamsDistanceUnit defines parameters for TourSearch.
type TourSearchParamsDistanceUnit string

// TourSearchParamsPointFilter defines parameters for TourSearch.
type TourSearchParamsPointFilter string
